<footer>
  <ul id="footer_list">
    <li class="footer_link"><a href="./index.php">Home</a></li>
    <li class="footer_link"><a href="./about.php">About</a></li>
    <li class="footer_link"><a href="./jobs.php">Jobs</a></li>
    <li class="footer_link"><a href="./enhancements.php">Enhancements</a></li>
    <li class="footer_link"><a href="./apply.php">Apply</a></li>
  </ul>
  <div id="copyright_container">
    <p>&#169; SQUARE ENIX LTD. All Rights Reserved.</p>
    <div id="github_container">
      <a
        href="https://github.com/dvaanc/computer-warriaz-project"
        target="_blank"
        ><img src="./images/github_logo.svg" alt="github logo"
      /></a>
      <span class="footer_link"
        ><a
          href="https://github.com/dvaanc/computer-warriaz-project"
          target="_blank"
          >Made by Computer Warriaz</a
        ></span
      >
    </div>
  </div>
</footer>
