<ul id="nav_list">
  <li class="nav_list_item"><a href="./index.php">Home</a></li>
  <li class="nav_list_item"><a href="./about.php">About</a></li>
  <li class="nav_list_item"><a href="./jobs.php">Jobs</a></li>
  <li class="nav_list_item"><a href="./enhancements.php">Enhancements</a></li>
  <li class="nav_list_item"><a href="./apply.php">Apply</a></li>
  <li class="pill_button">
    <a href="mailto:104349875@student.swin.edu.au">Contact</a>
  </li>
</ul>
