<?php
    function menu(){
        return '
        <ul id="nav_list">
        <li class="nav_list_item"><a href="./index.html">Home</a></li>
        <li class="nav_list_item"><a href="./about.html">About</a></li>
        <li class="nav_list_item"><a href="./jobs.html">Jobs</a></li>
        <li class="nav_list_item"><a href="./enhancements.html">Enhancements</a></li>
        <li class="nav_list_item"><a href="./apply.html">Apply</a></li>
        <li><a class="pill_button" href="mailto:104349875@student.swin.edu.au">Contact</a></li>
        </ul>';
    }
?>